# Generated by Django 4.2.2 on 2023-06-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecheraAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='descripcion',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='website',
            field=models.CharField(max_length=40),
        ),
    ]
