# Generated by Django 4.2.2 on 2023-06-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecheraAPP', '0002_alter_perfil_descripcion_alter_perfil_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
