# Generated by Django 4.2.2 on 2023-07-02 16:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecheraAPP', '0003_perfil_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='contenido',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='postImagenes'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subTitulo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
