# Generated by Django 4.2.2 on 2023-07-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TecheraAPP', '0007_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='mensaje',
            new_name='descripcion',
        ),
    ]
