# Generated by Django 4.2 on 2023-07-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecheraAPP', '0008_rename_mensaje_about_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
